name: ping-temperate
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

concurrency:
  group: ping-temperate
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Call health endpoint
        run: |
          set -euo pipefail
          echo "Pinging: $TARGET_URL"
          # Try a quick HEAD first; if that fails, fall back to a longer GET (cold start)
          curl -fIsS --connect-timeout 5 -m 10 \
            -H "X-Task-Secret: $TASK_SECRET" \
            "$TARGET_URL" -o /dev/null || \
          curl -fsS --retry 3 --retry-delay 5 --retry-all-errors -m 60 \
            -H "X-Task-Secret: $TASK_SECRET" \
            "$TARGET_URL" -o /dev/null
        
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          TASK_SECRET: ${{ secrets.TASK_SECRET }}
