name: ping-temperate

on:
  schedule:
    - cron: "*/5 * * * *"   # every 10 minutes (UTC)
  workflow_dispatch:          # allow manual runs

concurrency:
  group: ping-temperate
  cancel-in-progress: true

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Ping backend keep-alive (robust)
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}     # e.g. https://<backend>.onrender.com/tasks/warmup
          TASK_SECRET: ${{ secrets.TASK_SECRET }}   # same value as on your backend
        run: |
          set -euo pipefail
          echo "Pinging: $TARGET_URL"

          # Try a quick HEAD first (10s). If it fails (4xx/5xx/timeout), fall back to GET with retries.
          curl -fIsS --connect-timeout 5 -m 10 \
            -H "X-Task-Secret: $TASK_SECRET" \
            "$TARGET_URL" -o /dev/null || \
          curl -fsS --retry 5 --retry-delay 10 --retry-all-errors --retry-connrefused -m 120 \
            -H "X-Task-Secret: $TASK_SECRET" \
            "$TARGET_URL" -o /dev/null

